services:
  mysql-db:
    container_name: mysql-db
    build:
      dockerfile: DockerFile.mysql
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQLDB_DATABASE}
        MYSQL_USER: ${MYSQLDB_USER}
        MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
        MYSQL_HOST: "*"
    ports:
      - "3306:3306"
    restart: always
    networks:
      - wpnet
    depends_on:
      cert-gen:
        condition: service_completed_successfully

  cert-gen:
    build:
      dockerfile: DockerFile.gencerts
      args:
        USER_ID: ${USER_ID}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        ORGANIZATIONAL_UNIT: ${ORGANIZATIONAL_UNIT}
        COMMON_NAME: ${COMMON_NAME}
        EMAIL_ADDRESS: ${EMAIL_ADDRESS}
    volumes:
      - ./certs:/usr/local/bin/newcerts

networks:
  wpnet:
    driver: bridge