services:
  samba:
    container_name: samba
    env_file:
      - .env
    build:
      dockerfile: DockerFile.samba
      target: samba
      args:
        TOTAL_SAMBA_USERS: ${TOTAL_SAMBA_USERS}
        SAMBA_USER_1: ${SAMBA_USER_1}
        SAMBA_PASSWORD_1: ${SAMBA_PASSWORD_1}
        SAMBA_USER_2: ${SAMBA_USER_2}
        SAMBA_PASSWORD_2: ${SAMBA_PASSWORD_2}
        COMMON_NAME_CA: ${COMMON_NAME_CA}
        COMMON_NAME_SERVER: ${COMMON_NAME_SERVER}
        COMMON_NAME_CLIENT: ${COMMON_NAME_CLIENT}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        ORGANIZATIONAL_UNIT: ${ORGANIZATIONAL_UNIT}
        EMAIL_ADDRESS: ${EMAIL_ADDRESS}
        KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
    ports:
      - 445:445
      - 139:139
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
  #    networks:
  #      custom_net:
  #        ipv4_address: 10.5.0.5
  #    healthcheck:
  #      test: ["CMD","/usr/local/bin/healtchecksamba.sh"]
  #      interval: 2s
  #      timeout: 10s


  mysql-db:
    container_name: mysql-db
    env_file:
      - .env
    build:
      dockerfile: DockerFile.mysql
      target: mysql
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/cert
    depends_on:
      samba:
        condition: service_healthy


volumes:
  data:
    driver_opts:
      type: cifs
      o: username=admin,password=1234
      device: //localhost/cert_share/

#networks:
#  custom_net:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.5.0.0/16