services:
  mysql-db:
    container_name: mysql-db
    build:
      dockerfile: DockerFile.mysql
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    depends_on:
      cert-gen:
        condition: service_completed_successfully


  cert-gen:
    image: cert-gen
    build:
      dockerfile: DockerFile.gencerts
      args:
        COMMON_NAME_CA: ${COMMON_NAME_CA}
        COMMON_NAME_SERVER: ${COMMON_NAME_SERVER}
        COMMON_NAME_CLIENT: ${COMMON_NAME_CLIENT}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        ORGANIZATIONAL_UNIT: ${ORGANIZATIONAL_UNIT}
        EMAIL_ADDRESS: ${EMAIL_ADDRESS}
        KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
    volumes:
      - type: bind
        source: ./cert
        target: /var/lib/cert/
    entrypoint: /usr/local/bin/script.sh