FROM mysql:latest as mysql
#ARG VARS
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD

#ENV VARS
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

#Create dir if not exist
RUN mkdir -p /var/lib/cert

RUN chown -R mysql:root /var/lib/cert
RUN chmod -R 700 /var/lib/cert

#We have to name it like a,b,c... in order to keep the order
COPY ./setupssl.sh /docker-entrypoint-initdb.d/a.sh

RUN chmod +x /docker-entrypoint-initdb.d/*.sh