services:
  samba:
    container_name: samba
    env_file:
      - .env
    build:
      dockerfile: DockerFile.samba
      target: samba
      args:
        TOTAL_SAMBA_USERS: ${TOTAL_SAMBA_USERS}
        SAMBA_USER_1: ${SAMBA_USER_1}
        SAMBA_PASSWORD_1: ${SAMBA_PASSWORD_1}
        SAMBA_USER_2: ${SAMBA_USER_2}
        SAMBA_PASSWORD_2: ${SAMBA_PASSWORD_2}
        COMMON_NAME_CA: ${COMMON_NAME_CA}
        COMMON_NAME_SERVER: ${COMMON_NAME_SERVER}
        COMMON_NAME_CLIENT: ${COMMON_NAME_CLIENT}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        ORGANIZATIONAL_UNIT: ${ORGANIZATIONAL_UNIT}
        EMAIL_ADDRESS: ${EMAIL_ADDRESS}
        KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
    ports:
      - 445:445
      - 139:139
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - data:/mnt/cert_share
    healthcheck:
      test: ["CMD", "smbclient", "//localhost/cert_share", "-U", "${SAMBA_USER_1}%${SAMBA_PASSWORD_1}", "-c", "ls"]
      interval: 2s
      timeout: 10s
      retries: 3


  mysql-db:
    container_name: mysql-db
    env_file:
      - .env
    build:
      dockerfile: DockerFile.mysql
      target: mysql
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/cert
    depends_on:
      samba:
        condition: service_healthy

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ./custom-volume
      o: bind